runtime: python39
service: default

instance_class: F1

env_variables:
  FLASK_ENV: "production"

handlers:
- url: /static
  static_dir: static
- url: /.*
  script: auto

entrypoint: gunicorn -b :$PORT appnolla1:app --worker-class eventlet
