steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/medical-transcription-dashboard', '.']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/medical-transcription-dashboard']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'nollaapp'
      - '--image'
      - 'gcr.io/$PROJECT_ID/medical-transcription-dashboard'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--port'
      - '8084'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '1'
      - '--max-instances'
      - '10'
      - '--concurrency'
      - '80'
      - '--timeout'
      - '300'
      - '--set-env-vars'
      - 'FLASK_ENV=production,APP_VERSION=${_APP_VERSION},MEMORY_LIMIT_MB=2048'
      - '--set-secrets'
      - '/secrets/firebase-credentials.json=firebase-credentials:latest,OPENAI_API_KEY=openai-api-key:latest,SECRET_KEY=app-secret-key:latest'
      - '--allow-unauthenticated'

substitutions:
  _APP_VERSION: '1.0.0'

options:
  logging: CLOUD_LOGGING_ONLY

# Store images in Container Registry
images:
  - 'gcr.io/$PROJECT_ID/medical-transcription-dashboard'
