name: nolla-medical
region: nyc
services:
  - name: nolla-medical-web
    dockerfile_path: Dockerfile
    source_dir: .
    github:
      branch: main
      deploy_on_push: true
    health_check:
      http_path: /
    http_port: 8080
    instance_count: 1
    instance_size_slug: basic-xxs
    envs:
      - key: OPENAI_API_KEY
        scope: RUN_TIME
        type: SECRET
    routes:
      - path: /
